### ISSUE TITLE
Updates August 2018

### ISSUE THREAD

**Issue by hundsim** [raarts/expo-react-native-web#7]
Hi! Thanks for your efforts trying to merge with Expo and your blog post.

Do you have any updated insights to share, now 4-5 months after you created this repo, as to what would be the best suited strategy to re-use an expo app in a web context?

Thanks in advance! 🙏

**Comment by raarts** [comment]
@hundsim : Unfortunately the React Native platforms are maintained by multiple parties, most of which have shown no interest in working together, and merging the code bases. The Expo guys seem to be the ones most interested, but they are a small fish in the pond. 

So unfortunately I don't see any significant progress being made.

This repo does only work with react-navigation 1.x, so you *might* want to consider moving forward with that. If you want/need 2.x support, there is no out-of-the-box solution that I'm aware of.

React Native Web keeps getting improved and extended so that is moving along nicely.
Another library that is definitely worth keeping an eye on is [React Native Dom](https://github.com/vincentriemer/react-native-dom).

So conclusion is: for the moment you'll have to roll your own solution.

**Comment by hundsim** [comment]
Thanks a lot for that run-through, it really helps.
